baseurl = "https://happy-pare-84a35d.netlify.app"
title = "Security+"
author = "Kaz"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Weekly IT Study"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Downloads"
    url  = "#"
[[menu.main]]
    name = "Discord?"
    url  = "#"

